language: node_js


node_js:
  - 8

services:
  - docker

script:
  - yarn build
  - docker build . -t ui
  - docker tag ui corefantasy/ui

deploy:
  provider: script
  script: bash dockerPush.sh
  on:
    branch: master
