language: node_js

node_js:
  - 8

services:
  - docker

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn build
  - docker build . -t ui
  - docker tag ui corefantasy/ui

deploy:
  provider: script
  script: bash dockerPush.sh
  on:
    branch: master
