language: node_js

services:
  - docker

script:
  - npm build run
  - docker build . -t ui
  - docker tag ui corefantasy/ui

deploy:
  provider: script
  script: bash dockerPush.sh
  on:
    branch: master
